name: file_picker_platform_interface
description: A common platform interface for the file_picker plugin
homepage: https://github.com/miguelpruivo/plugins_flutter_file_picker/file_picker_platform_interface
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^1.0.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
